name: Larastan

on:
  - pull_request

jobs:
  larastan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - name: Install Dependencies
        working-directory: ./webApp
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --prefer-dist

      - name: PHPStan Analyse
        working-directory: ./webApp
        run: ./vendor/bin/phpstan analyse